#!/usr/bin/env bash

# Need to memorize dirname vs basename
# Should probably just add a card to memorize this as well
# How do you get the directory that the current script is running from
# The script assumes that there is a directory called runs that contains scripts to run
script_dir=$(cd $(dirname "${BASH_SOURCE[0]}") && pwd)
filter=""
dry="0"

# loop through args and set values as appropriate
while [[ $# > 0 ]]; do
	if [[ $1 == "--dry" ]]; then
		dry="1"
	else
		filter="$1"
	fi
	## shift the first argument away
	shift
done

log() { 
	if [[ $dry == "1" ]]; then
		echo "[DRY_RUN]: $@"
	else
		echo "$@"
	fi
}

execute() { 
	log "execute $@"
	if [[ $dry == "1" ]]; then
		return
	fi
	"$@"
}

echo "${script_dir} -- ${filter}"

cd $script_dir

scripts=$(find ./runs -maxdepth 1 -mindepth 1 -executable -type f)

for script in $scripts; do
	if echo "$script" | grep -qv "${filter}"; then
		log "filtering $script"
		continue
	fi

	execute ./$script
done
