#!/usr/bin/env bash

# From https://github.com/neovim/neovim/blob/master/BUILD.md 
if command -v apt-get &> /dev/null; then
  echo "apt-get found"
  sudo apt-get install ninja-build gettext cmake curl build-essential
elif command -v dnf; then
  echo "dnf found"
  sudo dnf -y install ninja-build cmake gcc make gettext curl glibc-gconv-extra git
fi
git clone https://github.com/neovim/neovim ~/personal/neovim
cd ~/personal/neovim
git fetch
git checkout stable

make CMAKE_BUILD_TYPE=RelWithDebInfo

# Default install location is /usr/local
sudo make install
